{% set name = "openal-soft" %}
{% set version = "1.21.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kcat/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8ac17e4e3b32c1af3d5508acfffb838640669b4274606b7892aa796ca9d7467f

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('openal-soft', max_pin='x.x') }}


requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -f ${PREFIX}/lib/cmake/OpenAL/OpenALConfig.cmake                             # [unix]
    - test -f ${PREFIX}/bin/altonegen                                                   # [unix]
    - test -f ${PREFIX}/bin/alrecord                                                    # [unix]
    - test -f ${PREFIX}/bin/openal-info                                                 # [unix]
    - if exist %LIBRARY_LIB%\\cmake\\OpenAL\\OpenALConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_BIN%\\altonegen.exe (exit 0) else (exit 1)                      # [win]
    - if exist %LIBRARY_BIN%\\alrecord.exe (exit 0) else (exit 1)                       # [win]
    - if exist %LIBRARY_BIN%\\openal-info.exe (exit 0) else (exit 1)                    # [win]

about:
  home: https://github.com/kcat/openal-soft
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: COPYING
  summary: 'OpenAL Soft is a software implementation of the OpenAL 3D audio API.'

  description: |
    OpenAL Soft is an LGPL-licensed, cross-platform, software implementation of
    the OpenAL 3D audio API. It's forked from the open-sourced Windows version
    available originally from openal.org's SVN repository (now defunct). OpenAL
    provides capabilities for playing audio in a virtual 3D environment. Distance
    attenuation, doppler shift, and directional sound emitters are among the
    features handled by the API. More advanced effects, including air absorption,
    occlusion, and environmental reverb, are available through the EFX extension.
    It also facilitates streaming audio, multi-channel buffers, and audio capture.
  doc_url: https://openal-soft.org
  dev_url: https://github.com/kcat/openal-soft

extra:
  recipe-maintainers:
    - martinRenou
    - Tobias-Fischer
